apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: repro-906
spec:
  resources: []
  # The fix: group, version, and kind MUST be inside 'schema'
  schema:
    apiVersion: v1alpha1
    kind: TestCluster
    group: k8s.test.com
    spec:
      baseCluster: BaseCluster
    types:
      # The Potential Bug: BaseCluster references KubeconfigRef
      BaseCluster:
        kubeconfigRef: KubeconfigRef | required=true
      KubeconfigRef:
        name: string | required=true
        namespace: string | required=true
