# 095708837592.dkr.ecr.us-west-2.amazonaws.com/kro@sha256:b341e340b84b26669cee337bb5ddbd54d83cd23529c9b8f1edf32f07ec383ef1
apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: my-application
spec:
  schema:
    apiVersion: v1alpha1
    kind: Application
    spec:
      name: string
      image: string | default="nginx"
      a:
        enums: '[]string'
        something: '[]string'

  resources:
    - id: replicaSetOne
      # forEach a field that enables iteration on a set of values (arrays or maps).
      # It can reference a field in the schema or a field from another resource.
      # You can use CEL macros to manipulate the values before the iteration is executed.
      # For example ${[1,2,3].map(x, x + 1)} will iterate using the values [2,3,4].
      #
      # Otherfields like includeWhen and excludeWhen can be used well.
      forEach: ${schema.spec.a.enums.map(x, x + 'michael').filter(x, x != 'bmichael').map(x, [x, x + x])}
      template:
        apiVersion: v1
        kind: Pod
        metadata:
          # On each iteration, the value of each.item will be the current item in the list.
          # Possible values are:
          # each.item:    will point to the current item in the list.
          # each.index:   will point to the index of the current item in the list.
          # each.length:  will expose the length of the list.
          # each.key:     will point to the key of the current item in the map.
          # each.value:   will point to the value of the current item in the map.
          name: ${schema.spec.name + '-' + each.item}
        spec:
          containers:
          - name: ${schema.spec.name + '-' + each.item}
            image: ${schema.spec.image}

    - id: replicaSetTwo
      forEach: ${schema.spec.a.something}
      template:
        apiVersion: v1
        kind: Pod
        metadata:
          name: ${schema.spec.name + '-' + each.item}
        spec:
          containers:
          - name: ${schema.spec.name + '-' + each.item}
            image: ${schema.spec.image}
